# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmes',
            options={'verbose_name': 'Filme', 'verbose_name_plural': 'Filmes'},
        ),
        migrations.AlterModelOptions(
            name='generos',
            options={'verbose_name': 'Genero', 'verbose_name_plural': 'Generos'},
        ),
        migrations.AlterField(
            model_name='filmes',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filme.Generos'),
        ),
    ]
