# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_auto_20171110_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmes',
            options={'ordering': ['filme'], 'verbose_name': 'Filme', 'verbose_name_plural': 'Filmes'},
        ),
        migrations.AlterModelOptions(
            name='generos',
            options={'ordering': ['genero'], 'verbose_name': 'Genero', 'verbose_name_plural': 'Generos'},
        ),
        migrations.AlterField(
            model_name='filmes',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filme.Generos'),
        ),
        migrations.AlterField(
            model_name='generos',
            name='genero',
            field=models.CharField(max_length=100, verbose_name='Genero'),
        ),
    ]
