# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0003_auto_20171110_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='filme',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='filmes',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filme.Generos'),
        ),
    ]
