# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0004_auto_20171110_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filme.Generos'),
        ),
    ]
