# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0005_auto_20171110_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmes',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='filmes',
            name='disponivel',
            field=models.CharField(default=True, max_length=10, verbose_name='Disponível'),
        ),
        migrations.AddField(
            model_name='filmes',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='static/imagens/'),
        ),
        migrations.AddField(
            model_name='filmes',
            name='lancamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='filmes',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filme.Generos'),
        ),
    ]
