# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0006_auto_20171121_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmes',
            name='ano',
            field=models.IntegerField(default=0, verbose_name='Ano'),
        ),
        migrations.AddField(
            model_name='filmes',
            name='sinopse',
            field=models.TextField(default='', max_length=300, verbose_name='sinopse'),
        ),
        migrations.AlterField(
            model_name='filmes',
            name='disponivel',
            field=models.CharField(default='Sim', max_length=10, verbose_name='Disponível'),
        ),
        migrations.AlterField(
            model_name='filmes',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filme.Generos'),
        ),
    ]
