# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0008_auto_20171124_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes_Comprados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=30, verbose_name='Nome')),
                ('data', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Filme_Comprado',
                'verbose_name_plural': 'Filmes_Comprados',
                'ordering': ['cliente'],
            },
        ),
        migrations.AlterField(
            model_name='filmes',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filme.Generos'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='filme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filme.Filmes'),
        ),
        migrations.AddField(
            model_name='filmes_comprados',
            name='filme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filme.Filmes'),
        ),
    ]
