# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0009_auto_20171130_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmes_comprados',
            name='filme',
        ),
        migrations.AddField(
            model_name='filmes',
            name='trailer',
            field=models.CharField(blank=True, max_length=100, verbose_name='trailer'),
        ),
        migrations.AlterField(
            model_name='filmes',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filme.Generos'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='filme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filme.Filmes'),
        ),
        migrations.DeleteModel(
            name='Filmes_Comprados',
        ),
    ]
