# Generated by Django 2.2.1 on 2019-05-20 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0010_auto_20171201_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filme.Generos'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='filme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filme.Filmes'),
        ),
    ]
